/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/divout.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text004.geometry} material={materials['Material.006']} position={[33.98, 25.89, -0.57]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/divout.glb')
