/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/div.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.005']} position={[31.65, 59.07, -1.05]} rotation={[Math.PI / 2, 0, 0]} scale={10} />
    </group>
  )
}

useGLTF.preload('/div.glb')
