/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Divout(props) {
  const { nodes, materials } = useGLTF('../../../../3d/divout.glb')
  return (
    <group {...props} dispose={null}>
      <mesh 
      geometry={nodes.Text004.geometry} 
      material={materials['Material.006']} 
      // rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('../../../../3d/divout.glb')
export default Divout