/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function H1(props) {
  const { nodes, materials } = useGLTF('../../../../3d/h1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh 
      geometry={nodes.Text007.geometry} 
      material={materials['Material.003']} 
      position={[-43,0,0]} 
      rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('../../../../3d/h1.glb')

export default H1