/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plano(props) {
  const { nodes, materials } = useGLTF('../../../../3d/plano.glb')
  return (
    <group {...props} dispose={null}>
      <mesh 
      geometry={nodes.Plane.geometry} 
      material={materials.Material} 
      position={[0,0,-10]} 
      rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('../../../../3d/plano.glb')
export default Plano
