/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("../../../../3d/textos.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Text008.geometry}
        material={materials["Material.004"]}
        position={[-20,0,0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("../../../../3d/textos.glb");

export default Model;
