/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { EpsBankElement } from '@stripe/react-stripe-js'
import { useFrame } from '@react-three/fiber';

export function Tie(props) {
  const { nodes, materials } = useGLTF('../../../../3d/tieFighter.glb')
  const tieref = useRef("<Mesh>(null)");
  let step =.2;
  let speed= 0.002/2;

useFrame(() => {
  if(!tieref.current){
    return;
  }
  step += speed;
  tieref.current.position.x = 380 * Math.asin(Math.sin(step))
  tieref.current.position.z = 50 * Math.asin(Math.cos(step))
  tieref.current.position.y = 100 * Math.asin(Math.cos(step))
 
  tieref.current.rotation.y += .002;
      tieref.current.rotation.z += .005;
})
  
  return (
    
       <group ref={tieref} scale={.8} {...props} dispose={null}>
    <pointLight 
      position={[-150,200,300]}
      args={['orange',-.15,840]}
    />
     <rectAreaLight 
     position={[0,10,0]}
      args={['green',5]}
    />
     <rectAreaLight 
     position={[0,-10,0]}
      args={['#99e2f0',5]}
    />
     <rectAreaLight 
     position={[10,0,5.9]}
      args={['#99e2f0',5]}
    />
      <rectAreaLight 
     position={[-10,0,5.9]}
      args={['rgb(240, 139, 139)',5]}
    />
      <mesh geometry={nodes.NGon03_bluehull.geometry} material={materials.bluehull} position={[0.06, 0.24, 2.57]} scale={9.74} />
      <mesh geometry={nodes.Object03_windowblack.geometry} material={materials.windowblack} position={[-0.05, 0.26, -0.76]} scale={9.74} />
      <mesh geometry={nodes.EnginGlo_gunred.geometry} material={materials.gunred} position={[-0.09, -3.29, 3.44]} rotation={[0, 0, -Math.PI]} scale={9.74} />
      <mesh geometry={nodes.Sphere03_bluehull.geometry} material={materials['bluehull.008']} position={[0.06, 0.24, -0.7]} scale={9.74} />
      <mesh geometry={nodes.Box08_darkbluehull.geometry} material={materials.darkbluehull} position={[0.06, 0.27, -0.74]} scale={9.74} />
      <mesh geometry={nodes.Object04_bluehull.geometry} material={materials['bluehull.003']} position={[-0.05, 0.24, -0.7]} scale={9.74} />
      <mesh geometry={nodes.Spot03_bluehull.geometry} material={materials['bluehull.006']} position={[0.06, 0.24, -0.68]} scale={9.74} />
      <mesh geometry={nodes.ChamferBox_engine.geometry} material={materials.engine} position={[-0.09, 0.31, -1.18]} scale={9.74} />
      <mesh geometry={nodes.Rectangle0_bluehull.geometry} material={materials['bluehull.001']} position={[-0.09, 0.3, -0.87]} scale={9.74} />
      <mesh geometry={nodes.Line60_solar.geometry} material={materials.solar} position={[0.06, 0.21, -0.71]} scale={9.74} />
      <mesh geometry={nodes.Line53_bluehull.geometry} material={materials['bluehull.002']} position={[0.06, 0.24, -0.66]} scale={9.74} />
      <mesh geometry={nodes.Circle07_bluehull.geometry} material={materials['bluehull.004']} position={[-0.05, 0.22, 2.42]} scale={9.74} />
      <mesh geometry={nodes.Sphere04_bluehull.geometry} material={materials['bluehull.007']} position={[-0.05, 0.24, -0.76]} scale={9.74} />
      <mesh geometry={nodes.Bulkhead_bluehull.geometry} material={materials['bluehull.005']} position={[0.06, 0.24, -0.66]} scale={9.74} />
    </group>
    
  )
}

useGLTF.preload('../../../../3d/tieFighter.glb')

export default Tie